<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Model\Bean;

use Test\Model\Bean\Generated\NewsBaseBean;

/**
 * The NewsBean class maps the 'news' table in database.
 */
class NewsBean extends NewsBaseBean
{

}