<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Model\Bean;

use Mouf\Security\UserService\UserInterface;
use Test\Model\Bean\Generated\UserBaseBean;

/**
 * The UserBean class maps the 'user' table in database.
 */
class UserBean extends UserBaseBean implements UserInterface
{
    /**
     * @return string
     */
    public function getLogin()
    {
        return $this->getEmail();
    }

}