<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Model\Dao;

use Test\Model\Dao\Generated\NewsBaseDao;

/**
 * The NewsDao class will maintain the persistence of NewsBean class into the news table.
 */
class NewsDao extends NewsBaseDao
{

    public function getLastNews(){
        return $this->find(null, [], "id desc")->take(0,3);
    }

}
